version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: billing-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/billing
      dockerfile: Dockerfile
    container_name: billing-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
